name: bookia
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.1

  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  go_router: ^16.2.2
  
  image_picker: ^1.2.0
  intl: ^0.20.2
  lottie: ^3.3.1
  pinput: ^5.0.2
  # shared_preferences: ^2.5.3
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1
  pretty_dio_logger: ^1.3.1


dev_dependencies:

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/screenshots/
